### ISSUE TITLE
Does not recognize little-endian byte array representation

### ISSUE THREAD

**Issue by gimesia** [avolantis/ts-guid#9]
Guid V4's byte array representation has its first 4 bytes in little-endian order. Atm the class can't parse V4 guids from byte arrays that matches this rule.

Guid.ToByteArray method in C#:
https://docs.microsoft.com/en-us/dotnet/api/system.guid.tobytearray?view=net-5.0

**Comment by bencelang** [comment]
This is a very interesting difference in behavior between different stacks. C# seems to be handling GUIDs not simply as an array of bytes internally thus the diff in representation. On the other hand, Java has those bytes big-endian.

There are two major directions we could follow with a fix implementation for this issue:

1. Have a globally configurable behavior of endianness (like the version handling currently). This comes with possible performance and complexity earnings on the cost of missing the features to support both at the same time.
2. Have all methods involving byte array operations configurable endianness options and preferably a globally configurable default.

**Comment by gimesia** [comment]
> This is a very interesting difference in behavior between different stacks. C# seems to be handling GUIDs not simply as an array of bytes internally thus the diff in representation. On the other hand, Java has those bytes big-endian.
> 
> There are two major directions we could follow with a fix implementation for this issue:
> 
> 1. Have a globally configurable behavior of endianness (like the version handling currently). This comes with possible performance and complexity earnings on the cost of missing the features to support both at the same time.
> 2. Have all methods involving byte array operations configurable endianness options and preferably a globally configurable default.

maybe we could have an optional `little-endian` bool parameter in `isByteArray()` function and each handler could call this function with different params...

![image](https://user-images.githubusercontent.com/50553665/100624201-6ff2ff00-3323-11eb-943f-02b4067c80f4.png)
